### ISSUE TITLE
How do we make sure the bookmarks are always shown?

### ISSUE THREAD

**Issue by cristicismas** [akshat46/FlyingFox#36]
First of all, I really like this project :) I've fiddled with it a bit locally so it suits my needs better, and everything is perfect, except the fact I don't know how to make the bookmarks always show. I've looked at the wiki and in the code, but I couldn't find anything to help me out. 

I've also tried changing this setting from the browser > rightclick near the url bar > bookmarks toolbar > always show, but that didn't change anything, and the setting seems to stay off?

I'm currently running latest firefox version on manjaro.

Any help would be appreciated, thanks!

**Comment by cristicismas** [comment]
I've finally found a way. In navbar.css: 
```css
toolbox[id="navigator-toolbox"]:hover #PersonalToolbar {
    opacity: 1;
    margin: 0 !important;
}
```
I just needed to remove the `:hover` and it's all good.
