### ISSUE TITLE
exclusively use the tst

### ISSUE THREAD

**Issue by mxrixs** [akshat46/FlyingFox#40]
So I am using an older config for tst by you and wanted to do so too in a new setup. There seems to be the need for css in the userchrome though and I dont really know what exactly I need

**Comment by akshat46** [comment]
You'll need `userchrome-hover` or `userchrome-static` based on which kind of sidebar you want. These would style the sidebar(remove header, remove splitter, etc.). Both of them also use `config.css` to set some variables mainly sidebar width(s).

**Comment by mxrixs** [comment]
ok so I have to put css into the extension itself and import userchrome-hover and config into my main file if I want it to be in hover mode? will the config affect anything else?

**Comment by akshat46** [comment]
Just realized I never removed tabline-removing code from userchrome-hover. Will fix that soon. Meanwhile, yeah include userchrome-hover and config.css in your userchrome. And remove line 51-62 from userchrome-hover. So these lines towards the end: 

```CSS
/* hide tabs */
.tabbrowser-tab {
    display: none;
}

#tabs-newtab-button {
    display: none;
}

.titlebar-spacer {
    display: none !important;
}
```
