### ISSUE TITLE
Aesthetic Problems

### ISSUE THREAD

**Issue by AbhijitSipahimalani** [akshat46/FlyingFox#65]
The open, close minimize buttons don't line up in color with the rest of the bar. 

Install Flying Fox and the TreeStyleTabs

Firefox Version
Firefox Nightly 89.0a1

**Comment by akshat46** [comment]
Yes thats a known issue with 89. A temporary fix for window-controls background color as showed in #60 
```css
toolbox#navigator-toolbox {
  border-bottom: solid var(--dividers) var(--sidebar-shadow-color) !important;
  background-color: var(--toolbar-bgcolor) !important;
}
```
Closing duplicate.
